- app/controllers/admin/cms/transcripts_controller.rb
- app/views/admin/cms/collections/_item_list.html.erb
- app/views/admin/cms/transcripts/_form.html.erb
https://www.pivotaltracker.com/story/show/149376333
General clean up and improved layout of content.
> improved display of uploaded content

- Capfile
- config/deploy.rb
- project/nsw-state-library-amplify/project.json
* Disabling the SCM setting in Capistrano in favour of the plugin
* Adding us as an extra admin for the project
* Removing the unwanted SAML login link
> v3.0.1: Minor post-launch tidyup

- app/models/transcript.rb
- app/views/admin/cms/collections/_item_list.html.erb
- app/views/admin/cms/transcripts/_transcript_file.html.erb
Shows the original image if there's no cropped image on the Admin index and edit and public show page.
> If there's no cropped image it falls back to the original image

- app/views/home/_transcript_list.html.erb
Fix for performance issue on the homepage.
> Reverted to the original image on the homepage

- app/models/transcript.rb
- app/views/home/_transcript_list.html.erb
Added cropped image to the homepage if exists, otherwise displays the original image.
> Added cropped image to homepage if exists

- app/jobs/voice_base_processing_job.rb
- app/services/voice_base/voicebase_api_service.rb
* Don't do check_progress unless we've got a valid voicebase_media_id.
* Queue transcripts for re-upload if necessary.
> [AM-137] Voicebase processing fixes

- app/assets/stylesheets/components/transcript_item.scss
- app/views/home/_transcript_list.html.erb
- app/views/home/_transcript_preview.html.erb
* Use [browser-based image lazyloading](https://caniuse.com/loading-lazy-attr) for images on the homepage
> [AM-146] Lazyloading for homepage images

- app/assets/stylesheets/admin_cms.scss
* Let Bootstrap etc control base position of modal popup
* Display modal popup over everything else
> [AM-154] ADMIN CMS: Adjust modal positioning

- app/models/transcript_line.rb
- db/migrate/20230404013631_add_pg_search_dmetaphone_support_functions.rb
- db/schema.rb
**_Description_**
I implemented dmetaphone algorithm to do the fuzzy search.
What it does is, It searches for the sound similarity of the keyword instead.
> [BUGFIX] Fuzzy search not working

- app/assets/stylesheets/application_v2.scss
- app/assets/stylesheets/components/filter.scss
- app/assets/stylesheets/objects/buttons.scss
- app/assets/stylesheets/objects/spacer.scss
- app/views/home/_filters.html.erb
- app/views/shared/_theme_filter_buttons.erb
**_Description:_**
Adds button theme filters in homepage.
It looks like this
It behaves like
https://user-images.githubusercontent.com/4254020/234765913-f9533319-f650-49a9-a01c-31c9458fb677.mp4
> Adds button theme filters in homepage

- package-lock.json
- package.json
- speech-to-text.js
* Remove unused packages
* Update Microsoft speech SDK
* speech-to-text.js: Infer language from filename
* Use pattern `locale-([a-z]+-[A-Z]+)`
* eg. `foo-locale-en-AU-abc123.wav`
> [AM-171] Language inference in Azure SDK script

- config/environments/production.rb
- config/initializers/bugsnag.rb
**Description:**
Users are unable to sign up due to a 500 error caused by
```
ActionView::Template::Error (Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true):
```
> [BUGFIX] Unable to signup users

- config/environments/production.rb
- config/initializers/bugsnag.rb
- Define default url options
- Include Bugsnug config
> Release v4.0.4

- app/assets/javascripts/admin/csv_export.js
- app/assets/stylesheets/admin_base.scss
- app/assets/stylesheets/components/report.scss
- app/controllers/admin/reports_controller.rb
- app/controllers/institutions_controller.rb
- app/models/user.rb
- app/views/admin/reports/edits.html.erb
- app/views/admin/reports/index.html.erb
- app/views/admin/reports/transcripts.html.erb
- app/views/admin/reports/users.csv.erb
- app/views/admin/reports/users.html.erb
- config/initializers/assets.rb
- config/routes.rb
* Add new admin/reports endpoint
* Reports per user
* CSV concatenate script
> [AM-195] User reports

- app/assets/javascripts/admin/csv_export.js
- app/assets/stylesheets/admin_base.scss
- app/assets/stylesheets/components/header.scss
- app/assets/stylesheets/components/report.scss
- app/controllers/admin/reports_controller.rb
- app/controllers/institutions_controller.rb
- app/models/user.rb
- app/views/admin/reports/edits.html.erb
- app/views/admin/reports/index.html.erb
- app/views/admin/reports/transcripts.html.erb
- app/views/admin/reports/users.csv.erb
- app/views/admin/reports/users.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/layouts/_account.html.erb
- app/views/shared/_header.html.erb
- config/initializers/assets.rb
- config/routes.rb
Identified possible fix for login link issue https://stackoverflow.com/questions/70498371/why-is-turbo-not-honoring-link-to-method-post
Updated login links accordingly
> [AM-193] Bugfix for Google login

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/admin_base.scss
- app/assets/stylesheets/components/will_paginate.scss
- app/controllers/admin/users_controller.rb
- app/controllers/application_controller.rb
- app/models/user.rb
- app/views/admin/users/index.html.erb
One of the slowest pages in admin is the user's admin page.
To mitigate the performance issue of the page, we implemented a pagination to this page as well.
> Paginate admin users lists

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/admin_base.scss
- app/assets/stylesheets/components/will_paginate.scss
- app/controllers/admin/stats_controller.rb
- app/services/stats_service.rb
- app/views/admin/stats/_flags_table.html.erb
- app/views/admin/stats/index.html.erb
- config/environments/production.rb
https://statelibrarynsw.atlassian.net/browse/AM-180
- Adding pagination to the flag table to mitigate slowness
- Improve some queries on stats on flag admin
- Implement Rails caching in Flag.stats_all
> AM-180: Improve flag stats page performance

- Gemfile
- Gemfile.lock
- app/jobs/sitemap_job.rb
- config/initializers/sidekiq.rb
This PR is for generating and pinging sitemap XML to search engines.
We have a job called `SitemapJob` that runs every day at midnight and updates our sitemap and pings it to the Google search engine.
> Generating Sitemap

- app/jobs/sitemap_job.rb
- public/robots.txt
- Remove sitemap pings
- Added sitemap.xml to robot.txt
> Sitemap fixes and improvements

- app/assets/javascripts/admin_base.js
- app/assets/javascripts/utils.js
- app/controllers/admin/institutions_controller.rb
- app/controllers/concerns/home_search.rb
- app/decorators/collection_decorator.rb
- app/decorators/institution_decorator.rb
- app/decorators/transcript_decorator.rb
- app/jobs/sitemap_job.rb
- app/models/institution.rb
- app/models/transcript.rb
- app/views/admin/cms/collections/_item.html.erb
- app/views/admin/cms/collections/show.html.erb
- app/views/admin/institutions/_form.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/staging.rb
- db/migrate/20240521044933_institution_hidden_flag.rb
- db/schema.rb
https://statelibrarynsw.atlassian.net/browse/AM-207
> Mark institution as hidden

- app/jobs/azure/speech_to_text_job.rb
Fast follow from this issue https://github.com/slnsw/amplify/pull/162. The issue is still occuring after the chages in the carrierwave download approach and adding a fallback. Now, were switching to use first the OpenURI approach since the carrierwave approach is not storing the disk locally hence, the error still persists
```
[ActiveJob] [Azure::SpeechToTextJob] [5b3735c0-7575-481a-8c1f-f988c94c648d] Performing Azure::SpeechToTextJob (Job ID: 5b3735c0-7575-481a-8c1f-f988c94c648d) from Sidekiq(default) enqueued at 2025-08-06T02:51:02.946644868Z with arguments: 982
[ActiveJob] [Azure::SpeechToTextJob] [5b3735c0-7575-481a-8c1f-f988c94c648d]   ^[[1m^[[36mTranscript Load (2.1ms)^[[0m  ^[[1m^[[34mSELECT "transcripts".* FROM "transcripts" WHERE "transcripts"."id" = $1 LIMIT $2^[[0m  [["id", …
```
> Use OpenURI to download remote audio file in SpeechToTextJob
